#!/usr/bin/env bash
set -e

BASE_DIR="$(dirname "$0")"
CURRENT_DIR="$(pwd)"
source ${BASE_DIR}/utils.sh

FULLPATH=$(realpath "${CURRENT_DIR}/${BASE_DIR}")
GOPATH=$(gopath $FULLPATH)

program="${0##*/}"
if [[ "$program" = "dep"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export GLIDE_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi

exec env GOPATH=$GOPATH dep "$@"
