[general]
# refresh rate, default 1h
default_refresh_delay = "1h" # format is number s,m,h (seconds, minutes, hours)
# default ttl in dns
default_ttl = 300
## logs 
log_level = "info"
log_path = "/var/log/dynamicdns.log" # can be file path or stdout"

# [[domain]]
# name="domain1.com"
# ip_provider = "livebox"
# dns_updater = "gandi"
# ip_version  = 4

# [[domain]]
# name="domain1.com"
# ip_provider = "interface:en0"
# dns_updater = "gandi"
# ip_version  = 6

# [[domain]]
# name="domain2.com"
# ip_provider = "livebox"
# dns_updater = "gandi"
# ttl=3000
# refresh_delay = 1h

# [[domain]]
# name="subdomain.domain2.com"
# ip_provider = "livebox"
# dns_updater = "gandi"
# ttl=3000
# refresh_delay = 1h
# ip_version  = 4

# todo : implement tld check with https://godoc.org/golang.org/x/net/publicsuffix
# todo : allow subdomains domains 


