[general]
# refresh rate, default 1h
default_refresh_delay = "1h"
default_ttl = 300
#ip_versions = []
log_level = "debug"
log_path = "./logs.log"

[[domain]]
name="domain1.fr"
ip_provider = "livebox"
dns_updater = "gandi"
# ttl =
# refresh_delay = 

[[domain]]
name="domain2.fr"
ip_provider = "livebox"
dns_updater = "gandi"
ttl=3000
# refresh_delay = 